services:
  db:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - melius-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: node:22-alpine
    container_name: melius-backend-dev
    working_dir: /app/apps/backend
    restart: always
    ports:
      - "3000:3000"
      - "5556:5556"
    env_file:
      - ./.env
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/apps/backend/node_modules
    depends_on:
      db:
        condition: service_healthy
    networks:
      - melius-network
    command: sh -c "apk add --no-cache openssl libc6-compat python3 make g++ && npm install -g pnpm && cd /app && pnpm install && cd /app/apps/backend && pnpm exec prisma generate && pnpm start:dev"

  web:
    image: node:22-alpine
    container_name: melius-web-dev
    working_dir: /app/apps/web
    restart: always
    ports:
      - "3001:3001"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3000
      - PORT=3001
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/apps/web/node_modules
      - /app/apps/web/.next
    depends_on:
      - backend
    networks:
      - melius-network
    command: sh -c "npm install -g pnpm && cd /app && pnpm install && cd /app/apps/web && pnpm dev"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - melius-network

networks:
  melius-network:
    driver: bridge
