export enum ErrorCode {
  // Auth / Email
  EMAIL_EXISTS = 'EMAIL_EXISTS',
  EMAIL_TOKEN_EXPIRED = 'EMAIL_TOKEN_EXPIRED',
  EMAIL_ALREADY_CONFIRMED = 'EMAIL_ALREADY_CONFIRMED',
  EMAIL_NOT_CONFIRMED = 'EMAIL_NOT_CONFIRMED',
  EMAIL_NOT_FOUND = 'EMAIL_NOT_FOUND',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  TOKEN_COOLDOWN = 'TOKEN_COOLDOWN',

  // Meetings
  SLOT_NOT_FOUND = 'SLOT_NOT_FOUND',
  SLOT_NOT_OWNED = 'SLOT_NOT_OWNED',
  DOC_PROFILE_NOT_FOUND = 'DOC_PROFILE_NOT_FOUND',
  SLOT_ALREADY_BOOKED = 'SLOT_ALREADY_BOOKED',
  MEETING_NOT_FOUND = 'MEETING_NOT_FOUND',
  MEETING_NOT_OWNED = 'MEETING_NOT_OWNED',
  MEETING_NO_THERAPIST = 'MEETING_NO_THERAPIST',
  MEETING_EXPIRED = 'MEETING_EXPIRED',
  MEETING_NOT_PENDING = 'MEETING_NOT_PENDING',
  CANCEL_NOT_ALLOWED_TOO_LATE = 'CANCEL_NOT_ALLOWED_TOO_LATE',
  INVALID_TIME_RANGE = 'INVALID_TIME_RANGE',
  AVAILABILITY_SLOT_OVERLAP = 'AVAILABILITY_SLOT_OVERLAP',

  // Payments
  PAYMENT_ALREADY_SUCCEEDED = 'PAYMENT_ALREADY_SUCCEEDED',
  PAYMENT_VERIFY_FAILED = 'PAYMENT_VERIFY_FAILED',
  PAYMENT_AMOUNT_MISMATCH = 'PAYMENT_AMOUNT_MISMATCH',
  P24_CONFIG_MISSING = 'P24_CONFIG_MISSING',
  PAYMENT_PROVIDER_DISABLED = 'PAYMENT_PROVIDER_DISABLED',
  PAYMENT_NOT_ALLOWED = 'PAYMENT_NOT_ALLOWED',
  THERAPIST_NOT_PUBLISHED = 'THERAPIST_NOT_PUBLISHED',
  SESSION_PRICE_NOT_SET = 'SESSION_PRICE_NOT_SET',

  // Rating
  RATING_ALREADY_EXISTS = 'RATING_ALREADY_EXISTS',
  RATING_MEETING_NOT_COMPLETED = 'RATING_MEETING_NOT_COMPLETED',
  USER_PROFILE_NOT_FOUND = 'USER_PROFILE_NOT_FOUND',
  RATING_MEETING_MISMATCH = 'RATING_MEETING_MISMATCH',

  // Doctors
  INVALID_DATE_RANGE = 'INVALID_DATE_RANGE',
  DOC_PROFILE_INCOMPLETE = 'DOC_PROFILE_INCOMPLETE',
  DOC_PROFILE_ALREADY_APPROVED = 'DOC_PROFILE_ALREADY_APPROVED',
  DOC_PROFILE_NOT_APPROVED = 'DOC_PROFILE_NOT_APPROVED',
  DOC_PROFILE_NOT_SUBMITTED = 'DOC_PROFILE_NOT_SUBMITTED',
  INVALID_REJECTION_REASON = 'INVALID_REJECTION_REASON',
}
