// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Home": {
    "startMatching": "Start matching",
    "matchTitle": "Matched for you",
    "matchDesc": "In a few simple steps",
    "verifiedTitle": "Verified",
    "verifiedDesc": "Licensed specialists",
    "timeNote": "Takes about 2 minutes • No registration to start.",
    "selectDateButton": "Select date",
    "backButton": "Back",
    "searchingButton": "Searching...",
    "searchTherapistButton": "Search for therapist",
    "docEmptyState": "No therapists available for the selected dates",
    "docPrevAria": "Previous therapist",
    "docNextAria": "Next therapist",
    "docIndicatorAria": "Go to therapist {index}"
  },
  "Stepper": {
    "step0": {
      "header": "Find clarity with <em>the right support.</em>",
      "subheader": "Answer a few thoughtful questions to get matched with a licensed therapist who truly fits your needs, personality, and preferences.",
      "quote": "This isn't about changing who you are — it's about understanding yourself better."
    },
    "step1": {
      "header": "What would you like to focus on?",
      "subheader": "Select the option that feels closest to what you're experiencing right now.",
      "quote": "Putting things into words is often the first step forward."
    },
    "step2": {
      "header": "When are you <em>free</em>?",
      "subheader": "Choose a preferred time range for your session.",
      "quote": "Taking time for yourself is an important step."
    },
    "step3": {
      "header": "Your Matches",
      "subheader": "We found {count} specialists based on your needs.",
      "quote": "Healing happens in connection. Finding someone who truly understands matters."
    }
  },
  "Problems": {
    "mood_disorders": "Mood",
    "anxiety_and_panic": "Anxiety & panic",
    "depression": "Depression",
    "trauma": "Trauma",
    "sleep_disorders": "Sleep",
    "addictions": "Addictions",
    "eating_disorders": "Eating & body image",
    "personality_disorders": "Self & identity",
    "family_and_relationship_issues": "Relationships & family",
    "life_crises": "Life crisis",
    "developmental_issues": "Childhood & development",
    "sexuality_and_related_issues": "Sex & intimacy",
    "lgbtqia_specific_issues": "LGBTQIA+",
    "personal_development": "Growth",
    "career_development": "Career",
    "neurobiological_disorders": "Neurology"
  },
  "DocCard": {
    "psychologist": "Psychologist",
    "psychotherapist": "Psychotherapist",
    "sexologist": "Sexologist",
    "today": "Today",
    "tomorrow": "Tomorrow",
    "bookSession": "Book Session",
    "availableSlots": "Available slots",
    "previous": "Previous",
    "next": "Next"
  },
  "DateRangePicker": {
    "today": "Today",
    "tomorrow": "Tomorrow",
    "nextWeek": "Next week",
    "quickSelect": "Quick Select",
    "selectedDate": "Selected date",
    "range": "Range",
    "from": "From",
    "to": "To"
  },
  "Header": {
    "loginButton": "Log in",
    "userName": "User"
  },
  "Errors": {
    "EMAIL_EXISTS": "Email address already exists",
    "EMAIL_TOKEN_EXPIRED": "Email verification token has expired",
    "EMAIL_ALREADY_CONFIRMED": "Email address is already confirmed",
    "EMAIL_NOT_CONFIRMED": "Email address is not confirmed",
    "EMAIL_NOT_FOUND": "Email address not found",
    "INVALID_CREDENTIALS": "Invalid email or password",
    "TOKEN_COOLDOWN": "Please wait before requesting another token",
    "REFRESH_EXPIRED": "Session expired, please log in again",
    "REFRESH_REUSED": "Invalid session detected",
    "REFRESH_INVALID": "Invalid session",
    "REFRESH_MISSING": "Session not found",
    "SLOT_NOT_FOUND": "Time slot not found",
    "SLOT_NOT_OWNED": "You don't have permission to modify this slot",
    "DOC_PROFILE_NOT_FOUND": "Therapist profile not found",
    "SLOT_ALREADY_BOOKED": "This time slot is already booked",
    "MEETING_NOT_FOUND": "Meeting not found",
    "MEETING_NOT_OWNED": "You don't have permission to access this meeting",
    "MEETING_NO_THERAPIST": "No therapist assigned to this meeting",
    "MEETING_EXPIRED": "This meeting has expired",
    "MEETING_NOT_PENDING": "Meeting is not in pending status",
    "CANCEL_NOT_ALLOWED_TOO_LATE": "Cannot cancel - too close to meeting time",
    "INVALID_TIME_RANGE": "Invalid time range",
    "AVAILABILITY_SLOT_OVERLAP": "Time slots cannot overlap",
    "PAYMENT_ALREADY_SUCCEEDED": "Payment has already been completed",
    "PAYMENT_VERIFY_FAILED": "Payment verification failed",
    "PAYMENT_AMOUNT_MISMATCH": "Payment amount does not match",
    "P24_CONFIG_MISSING": "Payment configuration is missing",
    "P24_REFUND_FAILED": "Refund failed",
    "PAYMENT_PROVIDER_DISABLED": "Payment provider is disabled",
    "PAYMENT_NOT_ALLOWED": "Payment is not allowed",
    "THERAPIST_NOT_PUBLISHED": "Therapist profile is not published",
    "SESSION_PRICE_NOT_SET": "Session price is not set",
    "RATING_ALREADY_EXISTS": "You have already rated this meeting",
    "RATING_MEETING_NOT_COMPLETED": "Cannot rate - meeting not completed",
    "USER_PROFILE_NOT_FOUND": "User profile not found",
    "RATING_MEETING_MISMATCH": "Rating does not match the meeting",
    "INVALID_DATE_RANGE": "Invalid date range",
    "DOC_PROFILE_INCOMPLETE": "Therapist profile is incomplete",
    "DOC_PROFILE_ALREADY_APPROVED": "Profile is already approved",
    "DOC_PROFILE_NOT_APPROVED": "Profile is not approved",
    "DOC_PROFILE_NOT_SUBMITTED": "Profile has not been submitted",
    "INVALID_REJECTION_REASON": "Invalid rejection reason",
    "INVALID_FILE_TYPE": "Invalid file type",
    "FILE_TOO_LARGE": "File is too large",
    "INVALID_REQUEST": "Invalid request",
    "NOT_FOUND": "Resource not found",
    "CONSENT_REQUIRED": "Consent is required"
  }
};
export default messages;